Press and release event
amrbashir/global-hotkey pull request #34
Opened 2023-10-16 20:35 UTC by chrisflatley

I've had look into Issue #9: separate press and release key events.

Status:

- Macos: Tested (on arm64) and seems to work correctly.  
- Linux: Untested, but the existing logic seems sound to just add to.
- Windows:  Not implemented. AFAIK you don't get a keyup (via WM_HOTKEY) but an approach is to repeatedly check the state of each previously key. (I guess not dissimilar to the X11 version). So you only have Pressed events on Windows at the min

I've implemented the `pub state` as suggested in the issue, but that means existing apps will get two events when they are expecting one.

See #9.

2023-10-16 23:36 UTC, amrbashir requested changes
Thank you, I will add the windows implementation later, just some missing docs and this should be good to go.

2023-10-16 23:36 UTC, amrbashir commented on src/lib.rs
> +}
missing docs

2023-10-16 23:36 UTC, amrbashir commented on src/lib.rs
> +    pub state: HotKeyState,
missing docs

2023-10-17 16:40 UTC, chrisflatley commented
Adding the doc was tougher than the code!

I wanted to test this in lInux but I've not had chance. I don't have a linux GUI around - not sure if VirtualBox would cut it.

2023-10-18 12:18 UTC, amrbashir commented on src/lib.rs
> +/// Describes a global hotkey event emitted when a [`HotKey`] is pressed or released.
```suggestion
/// Describes a global hotkey event emitted when a [`HotKey`] is pressed or released.
```

2023-10-18 12:18 UTC, amrbashir commented on src/lib.rs
> +    /// The event was triggered by the [`HotKey`] changing to this state.
```suggestion
    /// State of the associated [`HotKey`].
```

2023-10-18 12:18 UTC, amrbashir approved these changes
Thank you

2023-10-18 14:40 UTC, merged